/* Headless smoke test for dashboard.js: builds a tiny DOM stub, then asserts
   that every renderer runs without throwing against the embedded DATA.
   Run:  node dashboard/test_dashboard.js [page.html]
   Reads dashboard/index.html by default (generated by
   benchmark.dashboard_generator); pass a file name in the same directory
   (e.g. batch_pub_01.html) to check a batch or baseline page. */

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const target = process.argv[2] || "index.html";
const html = fs.readFileSync(path.join(__dirname, target), "utf8");
const start = html.indexOf("const DATA = ");
const end = html.indexOf("</script>", start);
if (start === -1 || end === -1) {
  console.error(`FAIL: could not find embedded DATA in ${target}`); process.exit(1);
}
let raw = html.slice(start + "const DATA = ".length, end).trim();
if (raw.endsWith(";")) raw = raw.slice(0, -1);
const DATA = JSON.parse(raw);
console.log(`embedded: ${DATA.entries.length} questions, ${Object.keys(DATA.summary.pipelines).length} pipelines`);

/* ── minimal DOM ─────────────────────────────────────────────────── */
function makeNode(tag) {
  const node = {
    tagName: tag, children: [], attributes: {}, style: { cssText: "" },
    _text: "", _html: "", title: "", value: "", options: [],
    appendChild(c) { this.children.push(c); if (tag === "select" && c.tagName === "option") this.options.push(c); return c; },
    setAttribute(k, v) { this.attributes[k] = v; },
    addEventListener() {},
    remove() {},
    querySelector(sel) {
      const want = sel.replace(".", "");
      for (const c of this.children) if ((c.attributes.class || "").includes(want)) return c;
      return null;
    },
    get textContent() { return this._text; },
    set textContent(v) { this._text = v; },
    get innerHTML() { return this._html; },
    set innerHTML(v) { this._html = v; this.children = []; },
  };
  return node;
}

const ids = ["meta", "cards", "byType", "legend", "costScatter", "delta",
  "backend", "llmActivity", "traceSelect", "traceMeta", "trace", "typeFilter",
  "outcomeFilter", "search", "resultsTable", "footMeta"];
const registry = {};
ids.forEach(id => { registry[id] = makeNode(id === "typeFilter" || id === "outcomeFilter" || id === "traceSelect" ? "select" : "div"); });

const document = {
  createElement: makeNode,
  createElementNS: (ns, tag) => makeNode(tag),
  createTextNode: text => ({ nodeType: 3, textContent: text }),
  getElementById: id => registry[id] || null,
  _listeners: {},
  addEventListener(evt, fn) { (this._listeners[evt] = this._listeners[evt] || []).push(fn); },
};

const sandbox = { document, console, JSON, Math, Object, Number, String, Array, DATA };
sandbox.window = sandbox;
vm.createContext(sandbox);

/* ── load dashboard.js then fire DOMContentLoaded ──────────────────── */
const js = fs.readFileSync(path.join(__dirname, "dashboard.js"), "utf8");
vm.runInContext(js, sandbox, { filename: "dashboard.js" });

let failed = 0;
for (const fn of (document._listeners.DOMContentLoaded || [])) {
  try { fn(); } catch (e) { failed++; console.error("FAIL boot:", e.message); }
}

/* ── assertions ───────────────────────────────────────────────────── */
function check(label, cond, detail = "") {
  console.log(`${cond ? "PASS" : "FAIL"} ${label}${detail ? " — " + detail : ""}`);
  if (!cond) failed++;
}
const cards = registry.cards.children;
/* Data-driven on purpose: a summary may legitimately hold one pipeline (a
   --pipelines agentic run), and the check that matters is that the renderers
   follow the data rather than a hard-coded expectation. */
const summary = DATA.summary || {};
const npipes = Object.keys(summary.pipelines || {}).length;
const ndelta = (summary.when_agents_matter || []).length;
check("stat cards match pipelines in summary", cards.length === npipes,
  `${cards.length} cards vs ${npipes} pipelines`);
check("byType svg present", registry.byType.children.length === 1);
check("legend entries match pipelines", registry.legend.children.length === npipes);
check("costScatter svg present", registry.costScatter.children.length === 1);
check("delta panel reflects when_agents_matter", registry.delta.children.length === (ndelta ? 2 : 1),
  `${registry.delta.children.length} nodes, ${ndelta} rows`);
check("trace options == entries", registry.traceSelect.options.length === DATA.entries.length);
check("trace waterfall has steps", registry.trace.children.length > 1, `${registry.trace.children.length} nodes`);
const tbody = registry.resultsTable.children.find(c => c.tagName === "tbody");
check("results table has rows", !!tbody && tbody.children.length === DATA.entries.length,
  `${tbody ? tbody.children.length : 0} rows`);
check("meta filled", registry.meta.innerHTML.includes("questions"));
check("footer filled", registry.footMeta.textContent.length > 20);
check("backend panel rendered", registry.backend.children.length > 0,
  `${registry.backend.children.length} nodes`);
check("provider contribution panel rendered", registry.llmActivity.children.length > 0,
  `${registry.llmActivity.children.length} nodes`);
check("trace names the graph store",
  (registry.traceMeta.textContent || "").includes("graph:"),
  registry.traceMeta.textContent);

console.log(failed ? `\n${failed} CHECK(S) FAILED` : "\nALL DASHBOARD CHECKS PASSED");
process.exit(failed ? 1 : 0);